name: CD - Deploy to Staging

on:
  # Isso só roda APÓS você fazer merge do PR (não durante o PR)
  push:
    branches: [staging]

env:
  DOCKER_IMAGE: therermz/admin-boiler-plate
  APP_NAME: app-name

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploy to Staging
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_SERVER_HOST }}
          username: ${{ secrets.STAGING_SERVER_USER }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          port: ${{ secrets.STAGING_SERVER_SSH_PORT }}
          script: |
            cd ~/repos/${{ env.APP_NAME }}
            docker pull ${{ env.DOCKER_IMAGE }}:staging
            docker-compose -f docker-compose.staging.yml pull
            docker-compose -f docker-compose.staging.yml up -d
            docker image prune -f
