name: Deploy app Staging

on:
  workflow_run:
    workflows: ["Test app"]
    types: ["completed"]

env:
  DOCKER_IMAGE: therermz/admin-boiler-plate # ALTERE COM O NOME DA nome-dockerhub/APLICAÇÃO
  APP_NAME: app-name

jobs:
  deploy:
    if: |
      github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'staging'

    runs-on: ubuntu-latest
    environment: staging_environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.DIR }}
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:staging
            ${{ env.DOCKER_IMAGE }}:${{ github.sha }}

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.STAGING_SERVER_HOST }}
          username: ${{ secrets.STAGING_SERVER_USER }}
          key: ${{ secrets.STAGING_SERVER_SSH_KEY }}
          port: ${{ secrets.STAGING_SERVER_SSH_PORT }}
          script: |
            cd ~/repos/${{ env.APP_NAME }}
            docker-compose -f ${env.APP_NAME}.staging.yml pull
            docker-compose -f ${{env.APP_NAME}}.staging.yml -p ${{ env.APP_NAME }} up -d
            docker image prune -f
